version: "3.9"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web console
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 2s
      timeout: 2s
      retries: 30


  dbt_banking:  # dagster + dbt + duckdb
    build: .
    container_name: dbt_banking
    depends_on:
      minio:
        condition: service_started
    environment:
      DAGSTER_HOME: /opt/dagster
      DBT_PROFILES_DIR: /dbt_banking/assignment1/.dbt
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: us-east-1
      S3_ENDPOINT_URL: http://minio:9000
      DUCKDB_S3_ENDPOINT: minio:9000
      DUCKDB_S3_URL_STYLE: path
      DUCKDB_S3_USE_SSL: "false"
    volumes:
      - .:/dbt_banking/   # your dbt + dagster code
      - dagster_home:/opt/dagster    # dagster instance state
    working_dir: /dbt_banking/
    ports:
      - "3000:3000"   # Dagster web UI
    # Start Dagster (dev = webserver + daemon in one process)
    command: >
      bash -lc "
        echo 'Waiting for MinIO...' &&
        until curl -sf http://minio:9000/minio/health/live >/dev/null; do sleep 1; done &&
        dagster dev -m dagster_project -h 0.0.0.0 -p 3000 &&
        tail -f /dev/null
      "

volumes:
  dagster_home:
  minio-data: